export type CountryOption = {
  code: string;
  label: {
    ru: string;
    en: string;
  };
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: "US", label: { ru: "США", en: "United States" } },
  { code: "GB", label: { ru: "Великобритания", en: "United Kingdom" } },
  { code: "DE", label: { ru: "Германия", en: "Germany" } },
  { code: "FR", label: { ru: "Франция", en: "France" } },
  { code: "AM", label: { ru: "Армения", en: "Armenia" } },
  { code: "GE", label: { ru: "Грузия", en: "Georgia" } },
  { code: "IT", label: { ru: "Италия", en: "Italy" } },
  { code: "ES", label: { ru: "Испания", en: "Spain" } },
  { code: "NL", label: { ru: "Нидерланды", en: "Netherlands" } },
  { code: "BE", label: { ru: "Бельгия", en: "Belgium" } },
  { code: "PL", label: { ru: "Польша", en: "Poland" } },
  { code: "UA", label: { ru: "Украина", en: "Ukraine" } },
  { code: "RU", label: { ru: "Россия", en: "Russia" } },
  { code: "TR", label: { ru: "Турция", en: "Turkey" } },
  { code: "IL", label: { ru: "Израиль", en: "Israel" } },
  { code: "IR", label: { ru: "Иран", en: "Iran" } },
  { code: "SA", label: { ru: "Саудовская Аравия", en: "Saudi Arabia" } },
  { code: "AE", label: { ru: "ОАЭ", en: "UAE" } },
  { code: "QA", label: { ru: "Катар", en: "Qatar" } },
  { code: "EG", label: { ru: "Египет", en: "Egypt" } },
  { code: "ZA", label: { ru: "ЮАР", en: "South Africa" } },
  { code: "NG", label: { ru: "Нигерия", en: "Nigeria" } },
  { code: "MA", label: { ru: "Марокко", en: "Morocco" } },
  { code: "DZ", label: { ru: "Алжир", en: "Algeria" } },
  { code: "ET", label: { ru: "Эфиопия", en: "Ethiopia" } },
  { code: "KE", label: { ru: "Кения", en: "Kenya" } },
  { code: "CN", label: { ru: "Китай", en: "China" } },
  { code: "JP", label: { ru: "Япония", en: "Japan" } },
  { code: "KR", label: { ru: "Южная Корея", en: "South Korea" } },
  { code: "IN", label: { ru: "Индия", en: "India" } },
  { code: "PK", label: { ru: "Пакистан", en: "Pakistan" } },
  { code: "BD", label: { ru: "Бангладеш", en: "Bangladesh" } },
  { code: "ID", label: { ru: "Индонезия", en: "Indonesia" } },
  { code: "MY", label: { ru: "Малайзия", en: "Malaysia" } },
  { code: "SG", label: { ru: "Сингапур", en: "Singapore" } },
  { code: "TH", label: { ru: "Таиланд", en: "Thailand" } },
  { code: "VN", label: { ru: "Вьетнам", en: "Vietnam" } },
  { code: "PH", label: { ru: "Филиппины", en: "Philippines" } },
  { code: "HK", label: { ru: "Гонконг", en: "Hong Kong" } },
  { code: "TW", label: { ru: "Тайвань", en: "Taiwan" } },
  { code: "AU", label: { ru: "Австралия", en: "Australia" } },
  { code: "AZ", label: { ru: "Азербайджан", en: "Azerbaijan" } },
  { code: "NZ", label: { ru: "Новая Зеландия", en: "New Zealand" } },
  { code: "CA", label: { ru: "Канада", en: "Canada" } },
  { code: "MX", label: { ru: "Мексика", en: "Mexico" } },
  { code: "BR", label: { ru: "Бразилия", en: "Brazil" } },
  { code: "AR", label: { ru: "Аргентина", en: "Argentina" } },
  { code: "CL", label: { ru: "Чили", en: "Chile" } },
  { code: "CO", label: { ru: "Колумбия", en: "Colombia" } },
  { code: "PE", label: { ru: "Перу", en: "Peru" } },
  { code: "VE", label: { ru: "Венесуэла", en: "Venezuela" } },
  { code: "SE", label: { ru: "Швеция", en: "Sweden" } },
  { code: "NO", label: { ru: "Норвегия", en: "Norway" } },
];
