from __future__ import annotations

from dataclasses import asdict, dataclass, field
from functools import lru_cache
from urllib.parse import urlparse
import re

from app.core.countries import normalize_country_code


@dataclass(slots=True)
class SourceProfile:
    canonical_name: str
    aliases: list[str]
    domains: list[str]
    handles: list[str] = field(default_factory=list)
    country: str | None = None
    region: str = "global"
    media_class: str = "digital_news"
    ownership_type: str = "unknown"
    state_affinity: str = "unknown"
    geopolitical_alignment: str = "unknown"
    confidence: float = 0.6
    notes: str | None = None


@dataclass(slots=True)
class SourceProfileMatch:
    profile: SourceProfile
    match_type: str
    matched_value: str

    def to_dict(self) -> dict:
        payload = asdict(self.profile)
        payload.update(
            {
                "match_type": self.match_type,
                "matched_value": self.matched_value,
                "primary_segment": infer_primary_segment(payload),
                "segment_tags": infer_segment_tags(payload),
            }
        )
        return payload


SOURCE_REGISTRY: list[SourceProfile] = [
    SourceProfile(
        canonical_name="Reuters",
        aliases=["reuters"],
        domains=["reuters.com"],
        handles=["reuters"],
        country="GB",
        region="global",
        media_class="wire",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.95,
    ),
    SourceProfile(
        canonical_name="Associated Press",
        aliases=["associated press", "ap news", "ap"],
        domains=["apnews.com"],
        handles=["ap"],
        country="US",
        region="north_america",
        media_class="wire",
        ownership_type="nonprofit",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.95,
    ),
    SourceProfile(
        canonical_name="Agence France-Presse",
        aliases=["afp", "agence france-presse"],
        domains=["afp.com"],
        handles=["afp"],
        country="FR",
        region="europe",
        media_class="wire",
        ownership_type="public",
        state_affinity="public_service",
        geopolitical_alignment="western",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="Bloomberg",
        aliases=["bloomberg"],
        domains=["bloomberg.com"],
        handles=["business", "bloomberg"],
        country="US",
        region="north_america",
        media_class="financial_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.92,
    ),
    SourceProfile(
        canonical_name="BBC",
        aliases=["bbc", "bbc news"],
        domains=["bbc.com", "bbc.co.uk"],
        handles=["bbcworld", "bbcnews"],
        country="GB",
        region="europe",
        media_class="public_broadcaster",
        ownership_type="public",
        state_affinity="public_service",
        geopolitical_alignment="western",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="The Guardian",
        aliases=["guardian", "the guardian"],
        domains=["theguardian.com"],
        handles=["guardian"],
        country="GB",
        region="europe",
        media_class="newspaper",
        ownership_type="nonprofit",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.9,
    ),
    SourceProfile(
        canonical_name="The New York Times",
        aliases=["new york times", "the new york times", "nyt"],
        domains=["nytimes.com"],
        handles=["nytimes"],
        country="US",
        region="north_america",
        media_class="newspaper",
        ownership_type="public_company",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.9,
    ),
    SourceProfile(
        canonical_name="The Washington Post",
        aliases=["washington post", "the washington post"],
        domains=["washingtonpost.com"],
        handles=["washingtonpost"],
        country="US",
        region="north_america",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="Financial Times",
        aliases=["financial times", "ft"],
        domains=["ft.com"],
        handles=["financialtimes"],
        country="GB",
        region="europe",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.9,
    ),
    SourceProfile(
        canonical_name="Wall Street Journal",
        aliases=["wall street journal", "wsj"],
        domains=["wsj.com"],
        handles=["wsj"],
        country="US",
        region="north_america",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="Politico",
        aliases=["politico"],
        domains=["politico.com", "politico.eu"],
        handles=["politico"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.87,
    ),
    SourceProfile(
        canonical_name="Foreign Policy",
        aliases=["foreign policy"],
        domains=["foreignpolicy.com"],
        handles=["foreignpolicy"],
        country="US",
        region="north_america",
        media_class="magazine",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.84,
    ),
    SourceProfile(
        canonical_name="Al Jazeera",
        aliases=["al jazeera", "aljazeera"],
        domains=["aljazeera.com"],
        handles=["ajenglish", "ajarabic"],
        country="QA",
        region="mena",
        media_class="broadcaster",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.85,
    ),
    SourceProfile(
        canonical_name="France 24",
        aliases=["france 24", "france24"],
        domains=["france24.com"],
        handles=["france24_en", "france24"],
        country="FR",
        region="europe",
        media_class="public_broadcaster",
        ownership_type="public",
        state_affinity="public_service",
        geopolitical_alignment="western",
        confidence=0.84,
    ),
    SourceProfile(
        canonical_name="Deutsche Welle",
        aliases=["deutsche welle", "dw"],
        domains=["dw.com"],
        handles=["dwnews"],
        country="DE",
        region="europe",
        media_class="public_broadcaster",
        ownership_type="public",
        state_affinity="public_service",
        geopolitical_alignment="western",
        confidence=0.86,
    ),
    SourceProfile(
        canonical_name="Anadolu Agency",
        aliases=["anadolu", "anadolu agency", "aa"],
        domains=["aa.com.tr"],
        handles=["anadoluagency"],
        country="TR",
        region="mena",
        media_class="wire",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="TRT World",
        aliases=["trt world", "trt"],
        domains=["trtworld.com"],
        handles=["trtworld"],
        country="TR",
        region="mena",
        media_class="public_broadcaster",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="Cumhuriyet",
        aliases=["cumhuriyet"],
        domains=["cumhuriyet.com.tr"],
        country="TR",
        region="mena",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="opposition",
        geopolitical_alignment="regional",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="Sozcu",
        aliases=["sozcu", "sözcü"],
        domains=["sozcu.com.tr"],
        country="TR",
        region="mena",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="opposition",
        geopolitical_alignment="regional",
        confidence=0.77,
    ),
    SourceProfile(
        canonical_name="Bianet",
        aliases=["bianet"],
        domains=["bianet.org"],
        country="TR",
        region="mena",
        media_class="digital_news",
        ownership_type="nonprofit",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.76,
    ),
    SourceProfile(
        canonical_name="TASS",
        aliases=["tass", "itar-tass"],
        domains=["tass.com", "tass.ru"],
        handles=["tassagency_en", "tassagency_en"],
        country="RU",
        region="post_soviet",
        media_class="wire",
        ownership_type="state",
        state_affinity="state",
        geopolitical_alignment="russian",
        confidence=0.97,
    ),
    SourceProfile(
        canonical_name="RIA Novosti",
        aliases=["ria novosti", "ria", "ria.ru"],
        domains=["ria.ru"],
        handles=["rianru"],
        country="RU",
        region="post_soviet",
        media_class="wire",
        ownership_type="state",
        state_affinity="state",
        geopolitical_alignment="russian",
        confidence=0.96,
    ),
    SourceProfile(
        canonical_name="RT",
        aliases=["rt", "russia today"],
        domains=["rt.com"],
        handles=["rt_com"],
        country="RU",
        region="post_soviet",
        media_class="broadcaster",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="russian",
        confidence=0.96,
    ),
    SourceProfile(
        canonical_name="Sputnik",
        aliases=["sputnik"],
        domains=["sputniknews.com"],
        handles=["sputnikint"],
        country="RU",
        region="post_soviet",
        media_class="wire",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="russian",
        confidence=0.95,
    ),
    SourceProfile(
        canonical_name="Meduza",
        aliases=["meduza"],
        domains=["meduza.io"],
        handles=["meduzaproject"],
        country="LV",
        region="europe",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="opposition",
        geopolitical_alignment="western",
        confidence=0.87,
    ),
    SourceProfile(
        canonical_name="TV Rain",
        aliases=["dozhd", "tv rain", "tvrain"],
        domains=["tvrain.tv"],
        handles=["tvrain"],
        country="NL",
        region="europe",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="opposition",
        geopolitical_alignment="western",
        confidence=0.84,
    ),
    SourceProfile(
        canonical_name="Novaya Gazeta Europe",
        aliases=["novaya gazeta europe", "novaya gazeta"],
        domains=["novayagazeta.eu"],
        handles=["novayagazeta_eu"],
        country="LV",
        region="europe",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="opposition",
        geopolitical_alignment="western",
        confidence=0.82,
    ),
    SourceProfile(
        canonical_name="The Moscow Times",
        aliases=["the moscow times", "moscow times"],
        domains=["themoscowtimes.com"],
        handles=["moscowtimes"],
        country="NL",
        region="europe",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.82,
    ),
    SourceProfile(
        canonical_name="Xinhua",
        aliases=["xinhua"],
        domains=["news.cn", "xinhuanet.com"],
        handles=["xhnews"],
        country="CN",
        region="east_asia",
        media_class="wire",
        ownership_type="state",
        state_affinity="state",
        geopolitical_alignment="chinese",
        confidence=0.97,
    ),
    SourceProfile(
        canonical_name="CGTN",
        aliases=["cgtn"],
        domains=["cgtn.com"],
        handles=["cgtnofficial"],
        country="CN",
        region="east_asia",
        media_class="broadcaster",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="chinese",
        confidence=0.95,
    ),
    SourceProfile(
        canonical_name="People's Daily",
        aliases=["people's daily", "peoples daily"],
        domains=["people.cn"],
        handles=["globaltimesnews"],
        country="CN",
        region="east_asia",
        media_class="newspaper",
        ownership_type="state",
        state_affinity="state",
        geopolitical_alignment="chinese",
        confidence=0.93,
    ),
    SourceProfile(
        canonical_name="Global Times",
        aliases=["global times"],
        domains=["globaltimes.cn"],
        handles=["globaltimesnews"],
        country="CN",
        region="east_asia",
        media_class="newspaper",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="chinese",
        confidence=0.92,
    ),
    SourceProfile(
        canonical_name="Caixin",
        aliases=["caixin"],
        domains=["caixinglobal.com"],
        handles=["caixin"],
        country="CN",
        region="east_asia",
        media_class="financial_news",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="chinese",
        confidence=0.7,
    ),
    SourceProfile(
        canonical_name="IRNA",
        aliases=["irna"],
        domains=["irna.ir"],
        handles=["irnanews_en"],
        country="IR",
        region="mena",
        media_class="wire",
        ownership_type="state",
        state_affinity="state",
        geopolitical_alignment="regional",
        confidence=0.96,
    ),
    SourceProfile(
        canonical_name="Press TV",
        aliases=["press tv", "presstv"],
        domains=["presstv.ir"],
        handles=["presstv"],
        country="IR",
        region="mena",
        media_class="broadcaster",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.95,
    ),
    SourceProfile(
        canonical_name="Tasnim News Agency",
        aliases=["tasnim", "tasnim news"],
        domains=["tasnimnews.com"],
        handles=["tasnimnews_en"],
        country="IR",
        region="mena",
        media_class="wire",
        ownership_type="state_aligned",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="Fars News Agency",
        aliases=["fars", "fars news"],
        domains=["farsnews.ir"],
        handles=["englishfars"],
        country="IR",
        region="mena",
        media_class="wire",
        ownership_type="state_aligned",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="Mehr News",
        aliases=["mehr news", "mehr"],
        domains=["mehrnews.com"],
        handles=["mehrnewscom"],
        country="IR",
        region="mena",
        media_class="wire",
        ownership_type="state_aligned",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.85,
    ),
    SourceProfile(
        canonical_name="Shargh Daily",
        aliases=["shargh", "shargh daily"],
        domains=["sharghdaily.com"],
        country="IR",
        region="mena",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.65,
    ),
    SourceProfile(
        canonical_name="The Jerusalem Post",
        aliases=["jerusalem post", "the jerusalem post"],
        domains=["jpost.com"],
        handles=["jerusalem_post"],
        country="IL",
        region="mena",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.76,
    ),
    SourceProfile(
        canonical_name="Haaretz",
        aliases=["haaretz"],
        domains=["haaretz.com"],
        handles=["haaretzcom"],
        country="IL",
        region="mena",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="The Times of Israel",
        aliases=["times of israel", "the times of israel"],
        domains=["timesofisrael.com"],
        handles=["timesofisrael"],
        country="IL",
        region="mena",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="The New Arab",
        aliases=["the new arab", "new arab"],
        domains=["newarab.com"],
        handles=["thenewarab"],
        country="GB",
        region="mena",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.74,
    ),
    SourceProfile(
        canonical_name="The Hindu",
        aliases=["the hindu"],
        domains=["thehindu.com"],
        handles=["the_hindu"],
        country="IN",
        region="south_asia",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="Times of India",
        aliases=["times of india"],
        domains=["timesofindia.indiatimes.com"],
        handles=["timesofindia"],
        country="IN",
        region="south_asia",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.68,
    ),
    SourceProfile(
        canonical_name="NDTV",
        aliases=["ndtv"],
        domains=["ndtv.com"],
        handles=["ndtv"],
        country="IN",
        region="south_asia",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.74,
    ),
    SourceProfile(
        canonical_name="Nikkei Asia",
        aliases=["nikkei", "nikkei asia"],
        domains=["asia.nikkei.com", "nikkei.com"],
        handles=["nikkei"],
        country="JP",
        region="east_asia",
        media_class="financial_news",
        ownership_type="public_company",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.82,
    ),
    SourceProfile(
        canonical_name="NHK",
        aliases=["nhk", "nhk world"],
        domains=["nhk.or.jp"],
        handles=["nhkworld_news"],
        country="JP",
        region="east_asia",
        media_class="public_broadcaster",
        ownership_type="public",
        state_affinity="public_service",
        geopolitical_alignment="regional",
        confidence=0.84,
    ),
    SourceProfile(
        canonical_name="Dawn",
        aliases=["dawn"],
        domains=["dawn.com"],
        handles=["dawn_com"],
        country="PK",
        region="south_asia",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="Geo News",
        aliases=["geo news", "geo"],
        domains=["geo.tv"],
        handles=["geonews_english"],
        country="PK",
        region="south_asia",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.66,
    ),
    SourceProfile(
        canonical_name="Arab News",
        aliases=["arab news"],
        domains=["arabnews.com"],
        handles=["arabnews"],
        country="SA",
        region="mena",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="pro_government",
        geopolitical_alignment="regional",
        confidence=0.74,
    ),
    SourceProfile(
        canonical_name="Al Arabiya",
        aliases=["al arabiya", "alarabiya"],
        domains=["alarabiya.net"],
        handles=["alarabiya_eng"],
        country="AE",
        region="mena",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.83,
    ),
    SourceProfile(
        canonical_name="The National",
        aliases=["the national", "thenationalnews"],
        domains=["thenationalnews.com"],
        handles=["thenationalnews"],
        country="AE",
        region="mena",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.68,
    ),
    SourceProfile(
        canonical_name="SANA",
        aliases=["sana", "syrian arab news agency"],
        domains=["sana.sy"],
        handles=["sanaajel"],
        country="SY",
        region="mena",
        media_class="wire",
        ownership_type="state",
        state_affinity="state",
        geopolitical_alignment="regional",
        confidence=0.93,
    ),
    SourceProfile(
        canonical_name="Ahram Online",
        aliases=["ahram online", "al-ahram"],
        domains=["english.ahram.org.eg", "ahram.org.eg"],
        country="EG",
        region="mena",
        media_class="digital_news",
        ownership_type="public",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="South China Morning Post",
        aliases=["south china morning post", "scmp"],
        domains=["scmp.com"],
        handles=["scmpnews"],
        country="HK",
        region="east_asia",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="Yonhap News Agency",
        aliases=["yonhap", "yonhap news"],
        domains=["yna.co.kr", "en.yna.co.kr"],
        handles=["yonhapnews"],
        country="KR",
        region="east_asia",
        media_class="wire",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.79,
    ),
    SourceProfile(
        canonical_name="Channel News Asia",
        aliases=["channel news asia", "cna"],
        domains=["channelnewsasia.com"],
        handles=["channelnewsasia"],
        country="SG",
        region="southeast_asia",
        media_class="broadcaster",
        ownership_type="public_company",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.67,
    ),
    SourceProfile(
        canonical_name="The Jakarta Post",
        aliases=["the jakarta post", "jakarta post"],
        domains=["thejakartapost.com"],
        country="ID",
        region="southeast_asia",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.76,
    ),
    SourceProfile(
        canonical_name="Agencia Brasil",
        aliases=["agencia brasil"],
        domains=["agenciabrasil.ebc.com.br"],
        country="BR",
        region="latin_america",
        media_class="wire",
        ownership_type="public",
        state_affinity="public_service",
        geopolitical_alignment="regional",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="Folha de S.Paulo",
        aliases=["folha de s paulo", "folha"],
        domains=["folha.uol.com.br"],
        country="BR",
        region="latin_america",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.79,
    ),
    SourceProfile(
        canonical_name="El Pais",
        aliases=["el pais", "elpais"],
        domains=["elpais.com"],
        handles=["el_pais"],
        country="ES",
        region="europe",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.83,
    ),
    SourceProfile(
        canonical_name="teleSUR",
        aliases=["telesur", "teleSUR"],
        domains=["telesurenglish.net", "telesur.net"],
        handles=["telesurenglish"],
        country="VE",
        region="latin_america",
        media_class="broadcaster",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="Daily Maverick",
        aliases=["daily maverick"],
        domains=["dailymaverick.co.za"],
        country="ZA",
        region="africa",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="Meydan TV",
        aliases=["meydan tv"],
        domains=["meydan.tv"],
        country="AZ",
        region="post_soviet",
        media_class="digital_news",
        ownership_type="nonprofit",
        state_affinity="opposition",
        geopolitical_alignment="western",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="Abzas Media",
        aliases=["abzas media", "abzasmedia"],
        domains=["abzas.org"],
        country="AZ",
        region="post_soviet",
        media_class="digital_news",
        ownership_type="nonprofit",
        state_affinity="opposition",
        geopolitical_alignment="western",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="Trend News Agency",
        aliases=["trend", "trend news agency"],
        domains=["trend.az"],
        country="AZ",
        region="post_soviet",
        media_class="wire",
        ownership_type="private",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.7,
    ),
    SourceProfile(
        canonical_name="APA",
        aliases=["apa", "apa.az"],
        domains=["apa.az"],
        country="AZ",
        region="post_soviet",
        media_class="wire",
        ownership_type="private",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.68,
    ),
    SourceProfile(
        canonical_name="OC Media",
        aliases=["oc media"],
        domains=["oc-media.org"],
        handles=["ocmediaorg"],
        country="GE",
        region="post_soviet",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="Fox News",
        aliases=["fox news"],
        domains=["foxnews.com"],
        handles=["foxnews"],
        country="US",
        region="north_america",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="western",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="Investopedia",
        aliases=["investopedia"],
        domains=["investopedia.com"],
        handles=["investopedia"],
        country="US",
        region="north_america",
        media_class="financial_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="The Hill",
        aliases=["the hill"],
        domains=["thehill.com"],
        handles=["thehill"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.82,
    ),
    SourceProfile(
        canonical_name="Newsmax",
        aliases=["newsmax", "newsmax.com"],
        domains=["newsmax.com"],
        handles=["newsmax"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="western",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="Crypto Briefing",
        aliases=["crypto briefing"],
        domains=["cryptobriefing.com"],
        handles=["cryptobriefing"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.76,
    ),
    SourceProfile(
        canonical_name="The Daily Free Press",
        aliases=["the daily free press", "daily free press"],
        domains=["dailyfreepress.com"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.63,
    ),
    SourceProfile(
        canonical_name="Montreal Gazette",
        aliases=["montreal gazette"],
        domains=["montrealgazette.com"],
        country="CA",
        region="north_america",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="The Globe and Mail",
        aliases=["the globe and mail", "theglobeandmail"],
        domains=["theglobeandmail.com"],
        country="CA",
        region="north_america",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.82,
    ),
    SourceProfile(
        canonical_name="The Age",
        aliases=["the age"],
        domains=["theage.com.au"],
        country="AU",
        region="asia_pacific",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="WAM",
        aliases=["wam"],
        domains=["wam.ae"],
        country="AE",
        region="mena",
        media_class="wire",
        ownership_type="state",
        state_affinity="state_aligned",
        geopolitical_alignment="regional",
        confidence=0.88,
    ),
    SourceProfile(
        canonical_name="The Straits Times",
        aliases=["the straits times", "straits times"],
        domains=["straitstimes.com"],
        handles=["straits_times"],
        country="SG",
        region="asia_pacific",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="Economic Times",
        aliases=["economic times", "the economic times"],
        domains=["economictimes.indiatimes.com"],
        country="IN",
        region="south_asia",
        media_class="financial_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.83,
    ),
    SourceProfile(
        canonical_name="Firstpost",
        aliases=["firstpost"],
        domains=["firstpost.com"],
        handles=["firstpost"],
        country="IN",
        region="south_asia",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.77,
    ),
    SourceProfile(
        canonical_name="Mint",
        aliases=["mint", "livemint"],
        domains=["livemint.com"],
        handles=["livemint"],
        country="IN",
        region="south_asia",
        media_class="financial_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.81,
    ),
    SourceProfile(
        canonical_name="Business Today India",
        aliases=["business today", "businesstoday"],
        domains=["businesstoday.in"],
        handles=["business_today"],
        country="IN",
        region="south_asia",
        media_class="business_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="DNA India",
        aliases=["dna", "dna india"],
        domains=["dnaindia.com"],
        country="IN",
        region="south_asia",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.73,
    ),
    SourceProfile(
        canonical_name="New Straits Times",
        aliases=["new straits times"],
        domains=["nst.com.my"],
        country="MY",
        region="asia_pacific",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="World Socialist Web Site",
        aliases=["world socialist", "world socialist web site", "wsws"],
        domains=["wsws.org"],
        handles=["wsws_updates"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="nonprofit",
        state_affinity="opposition",
        geopolitical_alignment="mixed",
        confidence=0.77,
    ),
    SourceProfile(
        canonical_name="Business Standard",
        aliases=["business standard"],
        domains=["business-standard.com"],
        handles=["bsindia"],
        country="IN",
        region="south_asia",
        media_class="business_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.8,
    ),
    SourceProfile(
        canonical_name="TheStreet",
        aliases=["thestreet", "the street"],
        domains=["thestreet.com"],
        handles=["thestreet"],
        country="US",
        region="north_america",
        media_class="business_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.78,
    ),
    SourceProfile(
        canonical_name="RealClearPolitics",
        aliases=["real clear politics", "realclearpolitics"],
        domains=["realclearpolitics.com"],
        handles=["realclearnews"],
        country="US",
        region="north_america",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="western",
        confidence=0.74,
    ),
    SourceProfile(
        canonical_name="News9 Live",
        aliases=["news9live", "news9 live"],
        domains=["news9live.com"],
        country="IN",
        region="south_asia",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="regional",
        confidence=0.74,
    ),
    SourceProfile(
        canonical_name="Anchorage Daily News",
        aliases=["anchorage daily news"],
        domains=["adn.com"],
        country="US",
        region="north_america",
        media_class="newspaper",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.72,
    ),
    SourceProfile(
        canonical_name="News18",
        aliases=["news18"],
        domains=["news18.com"],
        handles=["news18dotcom"],
        country="IN",
        region="south_asia",
        media_class="digital_news",
        ownership_type="private",
        state_affinity="mixed",
        geopolitical_alignment="regional",
        confidence=0.73,
    ),
    SourceProfile(
        canonical_name="WPLG",
        aliases=["wplg"],
        domains=["local10.com"],
        country="US",
        region="north_america",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.68,
    ),
    SourceProfile(
        canonical_name="KWTX",
        aliases=["kwtx"],
        domains=["kwtx.com"],
        country="US",
        region="north_america",
        media_class="broadcaster",
        ownership_type="private",
        state_affinity="independent",
        geopolitical_alignment="western",
        confidence=0.66,
    ),
]


def resolve_source_profile(
    *,
    source_name: str | None,
    url: str | None,
    handle: str | None = None,
    country_hint: str | None = None,
) -> dict | None:
    name = _normalize_text(source_name or "")
    domain = _extract_domain(url or "")
    normalized_handle = (handle or "").strip().lower().lstrip("@")

    if normalized_handle:
        handle_map = _handle_map()
        if normalized_handle in handle_map:
            return SourceProfileMatch(
                profile=handle_map[normalized_handle],
                match_type="handle",
                matched_value=normalized_handle,
            ).to_dict()

    if domain:
        domain_map = _domain_map()
        for candidate_domain, profile in domain_map.items():
            if domain == candidate_domain or domain.endswith(f".{candidate_domain}"):
                return SourceProfileMatch(
                    profile=profile,
                    match_type="domain",
                    matched_value=domain,
                ).to_dict()

    if name:
        for profile in SOURCE_REGISTRY:
            for alias in [profile.canonical_name, *profile.aliases]:
                normalized_alias = _normalize_text(alias)
                if not normalized_alias:
                    continue
                if name == normalized_alias or normalized_alias in name or name in normalized_alias:
                    return SourceProfileMatch(
                        profile=profile,
                        match_type="name",
                        matched_value=alias,
                    ).to_dict()

    return _fallback_profile(source_name=source_name, domain=domain, country_hint=country_hint)


def infer_primary_segment(profile: dict | None) -> str:
    if not profile:
        return "unknown"

    state_affinity = profile.get("state_affinity")
    geopolitical_alignment = profile.get("geopolitical_alignment")
    if state_affinity in {"state", "state_aligned", "pro_government"}:
        return "state_aligned"
    if state_affinity == "opposition":
        return "opposition"
    if geopolitical_alignment == "western":
        return "western_aligned"
    if state_affinity in {"independent", "public_service", "mixed"}:
        return "independent"
    return "unknown"


def infer_segment_tags(profile: dict | None) -> list[str]:
    if not profile:
        return ["unknown"]

    tags = {infer_primary_segment(profile)}
    state_affinity = profile.get("state_affinity")
    geopolitical_alignment = profile.get("geopolitical_alignment")

    if state_affinity in {"opposition", "independent", "public_service"}:
        tags.add("critical_non_state")
    if geopolitical_alignment == "western":
        tags.add("western_aligned")
    if state_affinity in {"state", "state_aligned", "pro_government"}:
        tags.add("state_aligned")
    return sorted(tag for tag in tags if tag)


@lru_cache
def _domain_map() -> dict[str, SourceProfile]:
    mapping: dict[str, SourceProfile] = {}
    for profile in SOURCE_REGISTRY:
        for domain in profile.domains:
            mapping[domain.lower()] = profile
    return mapping


@lru_cache
def _handle_map() -> dict[str, SourceProfile]:
    mapping: dict[str, SourceProfile] = {}
    for profile in SOURCE_REGISTRY:
        for handle in profile.handles:
            mapping[handle.lower().lstrip("@")] = profile
    return mapping


def _extract_domain(url: str) -> str:
    if not url:
        return ""
    parsed = urlparse(url if "://" in url else f"https://{url}")
    domain = (parsed.netloc or parsed.path).lower()
    return re.sub(r"^(www\.|m\.)", "", domain).strip("/")


def _normalize_text(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9а-яё\u0600-\u06ff\u4e00-\u9fff]+", " ", value.lower(), flags=re.IGNORECASE)
    return " ".join(normalized.split())


def _fallback_profile(*, source_name: str | None, domain: str, country_hint: str | None) -> dict | None:
    inferred_country = normalize_country_code(country_hint) or _infer_country_from_domain(domain)
    if not inferred_country:
        return None
    canonical_name = (source_name or domain or "").strip()
    if not canonical_name:
        return None
    profile = {
        "canonical_name": canonical_name,
        "aliases": [],
        "domains": [domain] if domain else [],
        "handles": [],
        "country": inferred_country,
        "region": _infer_region(inferred_country),
        "media_class": "digital_news",
        "ownership_type": "unknown",
        "state_affinity": "mixed",
        "geopolitical_alignment": _infer_geopolitical_alignment(inferred_country),
        "confidence": 0.35,
        "notes": "Auto-inferred from country hint or domain.",
    }
    profile["match_type"] = "fallback"
    profile["matched_value"] = country_hint or domain
    profile["primary_segment"] = infer_primary_segment(profile)
    profile["segment_tags"] = infer_segment_tags(profile)
    return profile


def _infer_region(country_code: str) -> str:
    region_map = {
        "AE": "mena",
        "AU": "asia_pacific",
        "AZ": "post_soviet",
        "BR": "latin_america",
        "CA": "north_america",
        "CN": "east_asia",
        "DE": "europe",
        "EG": "mena",
        "ES": "europe",
        "FR": "europe",
        "GB": "europe",
        "GE": "post_soviet",
        "HK": "east_asia",
        "ID": "asia_pacific",
        "IL": "mena",
        "IN": "south_asia",
        "IR": "mena",
        "JP": "east_asia",
        "KR": "east_asia",
        "LV": "europe",
        "MY": "asia_pacific",
        "NL": "europe",
        "PH": "asia_pacific",
        "PK": "south_asia",
        "QA": "mena",
        "RU": "post_soviet",
        "SA": "mena",
        "SG": "asia_pacific",
        "SY": "mena",
        "TR": "mena",
        "US": "north_america",
        "VE": "latin_america",
        "ZA": "africa",
    }
    return region_map.get(country_code, "global")


def _infer_geopolitical_alignment(country_code: str) -> str:
    if country_code in {"US", "GB", "FR", "DE", "NL", "ES", "CA", "AU", "JP", "KR", "SG", "LV"}:
        return "western"
    return "regional"


def _infer_country_from_domain(domain: str) -> str | None:
    if not domain:
        return None
    suffix_map = {
        ".ae": "AE",
        ".az": "AZ",
        ".co.uk": "GB",
        ".com.au": "AU",
        ".com.my": "MY",
        ".com.ph": "PH",
        ".co.za": "ZA",
        ".in": "IN",
        ".jp": "JP",
        ".kr": "KR",
        ".ru": "RU",
        ".sg": "SG",
        ".tr": "TR",
    }
    for suffix, country in suffix_map.items():
        if domain.endswith(suffix):
            return country
    return None
